// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package slack

import (
	"context"
	"sync"
)

var (
	lockSlackRepositoryMockGetWorkingCronChannel sync.RWMutex
)

// SlackRepositoryMock is a mock implementation of SlackRepository.
//
//     func TestSomethingThatUsesSlackRepository(t *testing.T) {
//
//         // make and configure a mocked SlackRepository
//         mockedSlackRepository := &SlackRepositoryMock{
//             GetWorkingCronChannelFunc: func(ctx context.Context) (string, error) {
// 	               panic("mock out the GetWorkingCronChannel method")
//             },
//         }
//
//         // use mockedSlackRepository in code that requires SlackRepository
//         // and then make assertions.
//
//     }
type SlackRepositoryMock struct {
	// GetWorkingCronChannelFunc mocks the GetWorkingCronChannel method.
	GetWorkingCronChannelFunc func(ctx context.Context) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetWorkingCronChannel holds details about calls to the GetWorkingCronChannel method.
		GetWorkingCronChannel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// GetWorkingCronChannel calls GetWorkingCronChannelFunc.
func (mock *SlackRepositoryMock) GetWorkingCronChannel(ctx context.Context) (string, error) {
	if mock.GetWorkingCronChannelFunc == nil {
		panic("SlackRepositoryMock.GetWorkingCronChannelFunc: method is nil but SlackRepository.GetWorkingCronChannel was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockSlackRepositoryMockGetWorkingCronChannel.Lock()
	mock.calls.GetWorkingCronChannel = append(mock.calls.GetWorkingCronChannel, callInfo)
	lockSlackRepositoryMockGetWorkingCronChannel.Unlock()
	return mock.GetWorkingCronChannelFunc(ctx)
}

// GetWorkingCronChannelCalls gets all the calls that were made to GetWorkingCronChannel.
// Check the length with:
//     len(mockedSlackRepository.GetWorkingCronChannelCalls())
func (mock *SlackRepositoryMock) GetWorkingCronChannelCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockSlackRepositoryMockGetWorkingCronChannel.RLock()
	calls = mock.calls.GetWorkingCronChannel
	lockSlackRepositoryMockGetWorkingCronChannel.RUnlock()
	return calls
}
